---
- name: Install base packages
  ansible.builtin.dnf:
    name: 
      - qemu-guest-agent
      - chrony
      - golang-github-prometheus-node-exporter
      - vim
      - htop
      - iperf3
      - tmux
      - tree
      - bash-completion
      - bind-utils
      - net-tools

- name: Enable and start services qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Enable and start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Enable and start node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true

- name: Enabel and start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
